name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [ '12', '10', '8' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install
      - run: if [ "$RUNNER_OS" != "windows-latest" ]; then npm test; fi
        shell: bash
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CREDS: ${{ secrets.CREDS }}
      BEAME_ENV: dev
      BEAME_AUTH_FQDN: ${{ secrets.BEAME_AUTH_FQDN }}
      BEAME_TESTS_LOCAL_FQDN: ${{ secrets.BEAME_TESTS_LOCAL_FQDN }}
      BEAME_TESTS_LOCAL_ROOT_FQDN: ${{ secrets.BEAME_TESTS_LOCAL_ROOT_FQDN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: Prepare test environment
        run: |
          echo "+ Deploying test creds"
          echo "$CREDS" | base64 --decode > creds.tgz
          mkdir -p ~/.beame/v2
          tar -xvzf creds.tgz -C ~/.beame/v2
          echo ""
          echo "+ Installing NGS"
          ( git clone -b dev --single-branch https://github.com/ngs-lang/ngs.git && cd ngs && ./install-linux.sh && make install )
      - name: Unit Tests
        run:  make unittests
      - name: Integration Tests
        run:  make clitests